# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-19 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_professor',
            new_name='is_lecturer',
        ),
    ]
