# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20160502_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
