# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='staff',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
