# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_about_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.TextField(max_length=3000)),
                ('staff', models.CharField(default=False, max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='about_message',
            field=models.TextField(max_length=3000),
        ),
    ]
